const FETCH_ARTICALE_LIST = 'articale/FETCH_ARTICALE_LIST';
const ARTICALE_DETAIL = 'articale/FETCH_ARTICALE_DETAIL';
const REFRESH = 'refresh';

export { FETCH_ARTICALE_LIST, ARTICALE_DETAIL, REFRESH };
